services:
  api:
    build:
      context: .
      dockerfile: ProductManagement.API/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
